feat(env.sh): Take a configuration from file
GluuFederation/gluu-passport-testing pull request #43
Opened 2020-10-27 12:20 UTC by kdhttps

Seperate configuration file to manage configurations

closes #36

2020-10-27 21:33 UTC, christian-hawk requested changes

2020-10-27 21:33 UTC, christian-hawk commented on env.sh
> +        if [ -z ${config_file+x} ];
1. Can you please check?
If I run `./env.s -c whatever`, output is:
```bash
PLEASE DO NOT INTERRUPT
============================================================================
Configuration is loading from whatever file
./env.sh: line 51: whatever: No such file or directory
```

2. Also, maybe load automatically from file (like `test.conf` if custom configuration file name not passed?)

2020-10-27 21:33 UTC, christian-hawk commented on config
> +PASSPORT_HOST=t1.techno24x7.com
maybe a more specific name like `tests.conf`?

2020-10-28 08:00 UTC, kdhttps commented on env.sh
> +        if [ -z ${config_file+x} ];
thank you for testing Chris. I'll fix it and take the `test.conf` file as a default

2020-10-28 08:00 UTC, kdhttps commented on config
> +PASSPORT_HOST=t1.techno24x7.com
Agree

2020-10-28 11:52 UTC, christian-hawk approved these changes
Good job @kdhttps  👍🏻

2020-10-28 11:53 UTC, merged