docs(Readme.Md): docs for configurations
GluuFederation/gluu-passport-testing pull request #48
Opened 2020-10-29 07:57 UTC by kdhttps

Added details about configuration in readme.md

closes #46

2020-10-29 14:24 UTC, christian-hawk requested changes

2020-10-29 14:24 UTC, christian-hawk commented on README.md
> +|**API_CLIENT_ID**|It is OP Client's ClientID which use by `auth-tdd-client` during passport auth flow|
Actually here is the **Gluu 4.1.1 Admin API** to automate user creation on **PROVIDER_HOST** server.

2020-10-29 14:34 UTC, kdhttps commented on README.md
> +|**API_CLIENT_ID**|It is OP Client's ClientID which use by `auth-tdd-client` during passport auth flow|
Pardon! Not getting you. you mean this API_Client is for automating user create on PROVIDER_HOST using Admin API, right?
If yes then the description for it like "It is OP Client's ClientID which is used to create user on SAML IDP Gluu Server using Gluu 4.1.1 Admin API".
is this ok?

2020-10-29 14:51 UTC, christian-hawk commented on README.md
> +|**API_CLIENT_ID**|It is OP Client's ClientID which use by `auth-tdd-client` during passport auth flow|
No problem, feel free to ask all questions. Lemme try to explain.
Here we a `gluu-server` instance (4.1.1) call `PROVIDER` (from passport provider), that acts as `IDP` (saml) or `OP`.
This `gluu-server` instance has an **Gluu Admin API** enabled,  test-suite uses `create_user.py`, and some other scripts to call **Gluu Admin API** w/ `API_CLIENT_ID` and `API_CLIENT_SECRET** as credentials.

2020-10-29 16:01 UTC, kdhttps commented on README.md
> +|**API_CLIENT_ID**|It is OP Client's ClientID which use by `auth-tdd-client` during passport auth flow|
Ok Got it, thank you :) .
So is this below description is ok?
`API_CLIENT_ID: "It is OP Client's ClientID which is used to create user on SAML IDP Gluu Server using Gluu 4.1.1 Admin API"`

2020-10-29 19:20 UTC, christian-hawk commented on README.md
> +|**API_CLIENT_ID**|It is OP Client's ClientID which use by `auth-tdd-client` during passport auth flow|
not sure thou. What do you think about sth like:

*Providers' gluu-server [Admin REST API](https://gluu.org/docs/gluu-server/4.1/api-guide/oxtrust-api/) `client_id` (used for automated user creation/deletion)*

?

2020-10-30 07:27 UTC, kdhttps commented on README.md
> +|**API_CLIENT_ID**|It is OP Client's ClientID which use by `auth-tdd-client` during passport auth flow|
Done, thank you :).

2020-10-30 13:13 UTC, christian-hawk approved these changes

2020-10-30 13:13 UTC, merged