feat(artifacts): fetch and save servers artifacts
GluuFederation/gluu-passport-testing pull request #61
Opened 2021-04-10 18:54 UTC by christian-hawk

Create function to fetch logs by ssh from both servers b4 destroy

closes #59

2021-04-12 07:38 UTC, kdhttps requested changes
Nice work mate @christian-hawk !!!

2021-04-12 07:38 UTC, kdhttps commented on env.sh
> +    scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@"$PROVIDER_HOST":/opt/gluu-server/opt/shibboleth-idp/logs/*.log ./server_artifacts/provider/.
@christian-hawk mate, need to update above 3 echo message as per log file.

2021-04-14 14:38 UTC, christian-hawk commented on env.sh
> +    scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@"$PROVIDER_HOST":/opt/gluu-server/opt/shibboleth-idp/logs/*.log ./server_artifacts/provider/.
changes done

2021-04-14 14:40 UTC, kdhttps approved these changes

2021-04-14 14:40 UTC, merged